server:
  port: 8003
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://EurekaServer7001.com:7001/eureka/,http://EurekaServer7002.com:7002/eureka/,http://EurekaServer7003.com:7003/eureka/
  instance:
    instance-id: MicroService-8003
    prefer-ip-address: true     #访问路径可以显示IP地址
info:
  app.name: xuyangliu-MicroService
  company.name: www.xuyangliu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
spring:
  application:
    name: MicroService-Producer
