server:
  port: 80
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://EurekaServer7001.com:7001/eureka/,http://EurekaServer7002.com:7002/eureka/,http://EurekaServer7003.com:7003/eureka/